"""Added initial table with changed fills

Revision ID: 88234085f662
Revises: c0ad3d3fccb1
Create Date: 2024-02-06 17:58:07.066365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88234085f662'
down_revision: Union[str, None] = 'c0ad3d3fccb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint('users_referral_code_key', 'users', type_='unique')
    op.drop_column('users', 'referral_expiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_expiration', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_referral_code_key', 'users', ['referral_code'])
    op.alter_column('users', 'referral_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
