"""Added initial table with new fills

Revision ID: c0ad3d3fccb1
Revises: e3c66c2c6ba2
Create Date: 2024-02-06 17:26:38.416537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ad3d3fccb1'
down_revision: Union[str, None] = 'e3c66c2c6ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_token', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_token', 'expiration_date')
    # ### end Alembic commands ###
